### ISSUE TITLE
SmaCC UI does not revert the grammar

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#54]
The "Versions" button in the SmaCC UI was a great addition.  But it doesn't work correctly (this is in the latest Pharo 7).

When I select a prior version, the `definitionComment` in the parser is indeed reverted, as you would expect.  But the text visible in the grammar pane of the UI does _not_ change.  To make the text change, I have to make a null edit to the name of the Parser Class, and save the (unchanged) name.  This forces the UI to refresh the grammar that it is displaying from the `definitionComment.`

**Comment by ThierryGoubier** [comment]
@apblack ,

The Versions button is based on an old request by @StephanEggermont , at a time where SmaCC code generation would frequently crash (and get you to loose the grammar along); it is particularly effective when used with GitFileTree, since then it can query through the git history as well as the change log (i.e. on disk + in image versions).

I'm just getting to gripes with using Pharo 7, and I'm starting to notice that many things are not working anymore with the text editor component of Morphic... I'll see to that.

**Comment by ThierryGoubier** [comment]
solved by d1432d9
